GET http://localhost:3000/appointments/

###

POST http://localhost:3000/appointments/
Content-Type: application/json

{
    "client_name": "M",
    "service": "Manicure",
    "status": "agendado",
    "service_date": "2020-06-05"
}

###
GET http://localhost:3000/appointments/2
###
